### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by ctdarwell** [jeremymcrae/ld_estimator#1]
Hi

I got the same error on pip with two Windows machines:

 ERROR: Command errored out with exit status 1:
     command: 'c:\users\windows\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Windows\\AppData\\Local\\Temp\\pip-install-0eemv2ot\\pysam\\setup.py'"'"'; __file__='"'"'C:\\Users\\Windows\\AppData\\Local\\Temp\\pip-install-0eemv2ot\\pysam\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Windows\AppData\Local\Temp\pip-pip-egg-info-90d2u7uw'
         cwd: C:\Users\Windows\AppData\Local\Temp\pip-install-0eemv2ot\pysam\
    Complete output (23 lines):
    # pysam: cython is available - using cythonize if necessary
    # pysam: htslib mode is shared
    # pysam: HTSLIB_CONFIGURE_OPTIONS=None
    '.' is not recognized as an internal or external command,
    operable program or batch file.
    '.' is not recognized as an internal or external command,
    operable program or batch file.
    # pysam: htslib configure options: None
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Windows\AppData\Local\Temp\pip-install-0eemv2ot\pysam\setup.py", line 241, in <module>
        htslib_make_options = run_make_print_config()
      File "C:\Users\Windows\AppData\Local\Temp\pip-install-0eemv2ot\pysam\setup.py", line 68, in run_make_print_config
        stdout = subprocess.check_output(["make", "-s", "print-config"])
      File "c:\users\windows\anaconda3\lib\subprocess.py", line 356, in check_output
        **kwargs).stdout
      File "c:\users\windows\anaconda3\lib\subprocess.py", line 423, in run
        with Popen(*popenargs, **kwargs) as process:
      File "c:\users\windows\anaconda3\lib\subprocess.py", line 729, in __init__
        restore_signals, start_new_session)
      File "c:\users\windows\anaconda3\lib\subprocess.py", line 1017, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by jeremymcrae** [comment]
Looks like it can't install another required package: pysam. Unfortunately, pysam isn't supported on windows.

If you are ok with not being able to easily check LD from VCF files, I could remove the pysam requirement, and then this should hopefully install.

**Comment by ctdarwell** [comment]
Could do that - I just convert VCF to list of lists (or tuples), right?

I would be quite happy on Linux also but get some error about pyhton setup.py egg_info!!
